### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by aulorbe** [learn-co-curriculum/dsc-1-11-08-feature-scaling-and-normalization#4]
"Even though this is not always a formal issue when estimating linear regression models, this can be an issues in more advanced machine learning models we'll cover later. "

should be 

"Even though this is not always a formal issue when estimating linear regression models, this can be an issue**s** in more advanced machine learning models we'll cover later."

**Comment by mathymitchell** [comment]
Thanks; good catch!
